version: 2

models:
  - name: int_accounts
    columns:
      - name: account_id
        tests:
          - unique:
              config:
                severity: error
          - not_null:
              config:
                severity: error